version: '3.10'
services:
  web:
   build: .
   command: python /a3/manage.py runserver 0.0.0.0:8003
   volumes:
     - .:/a3
   ports:
     - 8003:8003
   depends_on:
     - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"